### ISSUE TITLE
compile_usage_stats.pl problem with log

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/cap#1]
I'm receiving the following fairly regularly.

`unexpected end of string while parsing JSON string, at character offset 2 (before "refix}user"},"portal...") at /opt/cap/util/compile_usage_stats.pl line 75.`

I don't know which log line is generating the error, so can't provide any additional information yet.  It is possible a log line was only partly written before CAP was restarted at some point.  I don't know if this failure means that later lines in the same logfile aren't processed.

**Comment by SaschaAdler** [comment]
UsageStats are gone: https://github.com/crkn-rcdr/cap/commit/707d840fc776357d0ce1a977244b1a67f56c550d
