### ISSUE TITLE
Enhance image name with branch when not in main

### ISSUE THREAD

**Issue by brittnylapierre** [crkn-rcdr/cap#107]
grab from https://github.com/crkn-rcdr/cihm-metadatabus/blob/main/deployimage.sh 

include the git branch name (when not "main") within the image name

**Comment by RussellMcOrmond** [comment]
Notice that the above "deployimage" starts by doing a build, and doesn't rely on the build having already been done.  It usually does nothing but check the build was done and give it the right tag, but it is a good extra check.

I tend to also do a "pull" of the FROM in the Dockerfile before doing any of my testing, to ensure I'm starting from a security patched version of the base Docker image.
