### ISSUE TITLE
Update depositors.json (New depositor, French language).

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/cap#133]
New depositor: sru ?
English name: University of Regina Archives
French name: ?

The file https://github.com/crkn-rcdr/cap/blob/main/CAP/conf/depositors.json needs to be updated with the new depositor, and English and French labels.

Some of the existing labels never had French translations, and should probably be updated as well.
https://pub.canadiana.ca/search/?df=&dt=&usrlang=fr

**Comment by BeS4** [comment]
There isn't an official French version of the University of Regina Archives.  Should we just create our own translation? Does this information appear publicly on our website or is it just behind the scenes?

**Comment by RussellMcOrmond** [comment]
@BeS4 

The purpose of these fields is to be displayed on the website, and to display in the correct language when people change language.

Go to: https://pub.canadiana.ca/search/?df=&dt=&usrlang=en
Look on left where it says "Depositor".

Click French (top-right).

Look on the left where it now says "Fournisseur"

Now go to https://www.canadiana.ca/search/?df=&dt=&usrlang=en and do the same thing.

While "Canadiana.org" was never given a translation (The domain name rather than English or French text was used), "McGill University Archives" correctly becomes "Les archives de l'Université McGill"


Maybe we want the English name displayed when the page is in French.  But it should be a deliberate decision, as the label is public on the website.

**Comment by nataliemacdonald** [comment]
I just confirmed with Jason that we do not translate institutions if they do not have official translations. So, in case this case "University of Regina Archives" should appear on both the English and French versions of Canadiana. Since McGill has an official translated name, we used that for the French side.

**Comment by RussellMcOrmond** [comment]
Thanks.

I added @jjfriedman to review https://github.com/crkn-rcdr/cap/pull/137  , but I suspect all is well and we are ready to move forward.


I've created a new config for https://admin.canadiana.ca/packaging (and cleaned up the titles to be more consistent).
I only created a config for DC.  I hope we can move to DC-only right away with this new depositor.
