### ISSUE TITLE
XSS vulnerability on search page

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/cap#14]
Populating the search term query string fields with URL-escaped HTML (e.g. `http://online.canadiana.ca/search/?q0.0=%3E%3Cimg&q1.0=src%3Dx&q2.0=onerror%3Dalert(%27ismailtasdelen%27)%3E`) causes the HTML to be generated in (presumably) the search results title, etc.

**Comment by RussellMcOrmond** [comment]
I went looking and thought I found where the "q" parameters were being handled.

https://github.com/crkn-rcdr/cap/blob/c141bac1ab8b1f2de4f6e898a57e5179e5e7e592/CAP/lib/CIHM/Access/Search/Query.pm#L134-L153

But... couldn't figure out what was using that function.  Seems it is specific to the handling of Catalyst models and Adaptors https://github.com/crkn-rcdr/cap/blob/main/CAP/lib/CAP/Model/Search.pm

**Comment by RussellMcOrmond** [comment]
An FYI.

https://www.openbugbounty.org/search/?search=canadiana.ca

**Comment by brittnylapierre** [comment]
Hey Russell! Can you check my potential fix on the test environment? I pushed a potential fix to test from this branch: https://github.com/crkn-rcdr/cap/pull/143

I can push this to prod if you agree that it is ready.

**Comment by RussellMcOrmond** [comment]
Not a problem 
* https://www.canadiana.ca/?userlang=%22%3E%3Csvg%20onload=confirm(/OPEN%20BUGBOUNTY/)%3E  


Fixed:
* https://www.canadiana.ca/search/?q1.0=onload=alert(%27OPENBUGBOUNTY%27)%3E&q0.0=%3E%3Csvg
* https://www-test.canadiana.ca/search/?q1.0=onload=alert(%27OPENBUGBOUNTY%27)%3E&q0.0=%3E%3Csvg

Fixed:
* https://www.canadiana.ca/search/?q2.0=onerror=prompt(1);%3E&q1.0=src=a&q0.0=%3E%3Cimg
* https://www-test.canadiana.ca/search/?q2.0=onerror=prompt(1);%3E&q1.0=src=a&q0.0=%3E%3Cimg

Last is the same -- based on the query being sent back into the HTML without being escaped.
