### ISSUE TITLE
robots.txt disallows indexing of search tips.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/cap#28]
Example: http://www.canadiana.ca/robots.txt

The 'Disallow: /search' ends up disallowing http://www.canadiana.ca/search-tips which is in http://www.canadiana.ca/sitemap/static.xml

Possibly a missing / at the end of the disallow?

**Comment by SaschaAdler** [comment]
I think I've sorted this out. Let me know otherwise.

**Comment by RussellMcOrmond** [comment]
I'll confirm with Google's webmaster tools after Monday's launch of the new version of CAP.

**Comment by RussellMcOrmond** [comment]
Confirmed crawl allowed.
