### ISSUE TITLE
Decommission cdn.canadiana.ca

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/cap#31]
We set this up as a method to allow non-platform staff to upload files to be offered from the website.  With CRKN the main website is hosted separate from platform, so this is no longer needed.

As part of the rebrand #30 , references will be removed from CAP.  We can then determine if anything else references these files, and then decommission.

**Comment by SaschaAdler** [comment]
Rebrand is committed to master.

**Comment by RussellMcOrmond** [comment]
This is now a systems issue to remove the proxy/etc.

**Comment by RussellMcOrmond** [comment]
The only links in the logs I find interesting are these:

66.220.149.38 - - [01/Apr/2020:20:43:36 +0000] "GET /co/crkn_full.png HTTP/1.1" 200 31232 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"

Is it possible that Facebook is pointing to that logo somehow?

I see other bookmarks, which suggests I should add cdn.canadiana.ca to our list of unused domains to redirect to www.canadiana.ca/
