### ISSUE TITLE
Allow prefix in front of domains for CAP handled sites

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/cap#32]
It is sometimes valuable to stand up an additional CAP to demonstrate and allow wider testing of new features or page designs.  As we are moving to https and have a certificate that is *.canadiana.ca , and have HAProxy handling those domains, we will want the demo to fit within that name.

A proposal is to allow an environment variable defined prefix in front of the name.

environment:   CAP_.....::domain_prefix=demo-

The above would allow demo-www.canadiana.ca to be treated the same as www.canadiana.ca, and so-on through all the domains.

Allowing the prefix to be an optional environment variable allows us to potentially set up multiple technology previews at the same time.

**Comment by SaschaAdler** [comment]
This has been working for some time now.
