### ISSUE TITLE
Remove legacy ZFS file download support.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/cap#36]
I believe it is time to declare the adoption of Swift as production, and assume we will no longer be attempting to point patrons at servers using ZFS.

**Comment by SaschaAdler** [comment]
I'll include this as part of the `pasplit` branch.

**Comment by SaschaAdler** [comment]
I don't think the `pasplit` branch is current any more, and I'd rather just do this when it's safe to. ZFS support was helpful during the December Swift troubles.

Let me know, though, and I'll remove it.

**Comment by RussellMcOrmond** [comment]
Soon enough with P/A split we will have Access files separate from Preservation files, and that temporary hack won't work.

We should have a tag to remember this code if we need to think about it in the future, but otherwise clean it up from `main` as it will make next steps easier the cleaner CAP is.
