### ISSUE TITLE
uri_for called with undef argument at lib/CAP/Controller/View.pm line 165.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/cap#39]
https://github.com/crkn-rcdr/cap/blob/893deffd4fd5e193801a102341f2a8f076a1f931/CAP/lib/CAP/Controller/View.pm#L165

The error in the subject can be found the `docker logs`, including in the new demo.

**Comment by RussellMcOrmond** [comment]
Here is an example -- at the moment there isn't sufficient documents to do a random, so it fails...

https://sve-demo.canadiana.ca/viewrandom

**Comment by SaschaAdler** [comment]
We don't advertise /viewrandom and from what I can tell it fails only when a portal doesn't have anything in it? I can fix this but I'm not sure how important it is.

**Comment by RussellMcOrmond** [comment]
Not important.  Just worth keeping unassigned as something to fix when someone is bored.

**Comment by brittnylapierre** [comment]
Noticed https://sve-test.canadiana.ca/viewrandom is broken I will look into it

**Comment by brittnylapierre** [comment]
It was related to the pdf bug
