### ISSUE TITLE
Allow both single and multi-page PDF downloads.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/cap#57]
I'm working on the microservice that will import OCR data from legacy preservation https://github.com/crkn-rcdr/Access-Platform/issues/153

When I went to test the download via https://www-demo.canadiana.ca/view/oocihm.8_04937_411/2?r=0&s=1 I only see the multi-page download and not also the single-page download.

**Comment by RussellMcOrmond** [comment]
#58

**Comment by SaschaAdler** [comment]
Closed by #58.
