### ISSUE TITLE
Solr search queries generating errors

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/cap#72]
From the logs:

`org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Cannot parse 'collection:(monog') as tempxtestxtable where 1=1-- -)': Encountered " ")" ") "" at line 1, column 52.`

`org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Cannot parse 'collection:(monog and 1=2-- -)': Encountered " ")" ") "" at line 1, column 29.`

`org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Cannot parse 'collection:(monog' and 1=1-- -)': Encountered " ")" ") "" at line 1, column 30.`

I suspect this is more sanity checking needed for search queries before sending them.  May relate to #14

**Comment by RussellMcOrmond** [comment]
Note also that "pkey", "depository", "collection" must match the standard "Slug" filter, so there is a regular expression already used in https://access.canadiana.ca/ that defines what characters are allowed (and quotes and brackets are obviously not allowed).

Looking for where this validation should happen, and it looks like handle_params() is the right place.

https://github.com/crkn-rcdr/cap/blob/a148d1c1f8f89feb000d41b6451fecbc86c834fa/CAP/lib/CAP/Controller/Search.pm#L107-L122


If something should be a singleton, then that should be checked as well: 

https://www.canadiana.ca/search?pkey=test1&pkey=test2

Maybe: ```pkey  =>  (pop make_slugs($params->{pkey})) // ""```

Where `sub make_slug()` returns an array of strings which have been stripped of any character not allowed to be in a slug. It handles arrays (creating one if only a string was passed in) means the same function can be used for "depositor" and "collection".

First make_array(), then loop through array fixing each member.

Note: these parameters are also all displayed, so the filtering will also help with #14 ("%" is not one of the allowed character for any of the parameter value types).

**Comment by brittnylapierre** [comment]
Hey Russell! Can you check my potential fix on the test environment? I pushed a potential fix to test from this branch: https://github.com/crkn-rcdr/cap/pull/143 

https://www-test.canadiana.ca/search?pkey=test1&pkey=test2
