### ISSUE TITLE
Tell OpenSeadragon to attempt to make anonymous cross-origin requests

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/cap#74]
Apparently Canadiana is still being used under a proxy in some places. Since we're no longer directly manipulating the `src` attribute of an `img` tag but doing requests through JavaScript, these requests are Cross-Origin if the site is proxied. OpenSeadragon has a `crossOriginPolicy` option which lets it try to make a Cross-Origin request. Our image servers are configured with `access-control-allow-origin: *` headers, and so I think `crossOriginPolicy` can be set to `Anonymous`.

**Comment by RussellMcOrmond** [comment]
@EmilieLFunston reports that there was a report of a problem on Tuesday, so not sure what we have remaining to do.
@jjfriedman will want to follow this PR as well.

**Comment by RussellMcOrmond** [comment]
Additional thought:  These proxies may be caching parts of the site such that they aren't showing patrons the latest version. I don't know that there is much we can do if that is the case.  Sascha is already using a cache-busting technique for some of the Javascript code..

**Comment by jjfriedman** [comment]
@EmilieLFunston sent a message out to the collections list on Friday. Between that and advising the knowledge base providers directly, hopefully we've solved this issue for users at our member institutions. She asked members to contact me if they had any questions/concerns. I'll let you know if I receive any.
