### ISSUE TITLE
Confirm environment variables and databases that are still being used.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/cap#75]
A search for [Collections_server](https://github.com/search?q=org%3Acrkn-rcdr+Collections_server&type=code) only shows this database referenced in the Dockerfile.  Is this used in the code any more, and can it be removed?

Can the `cap_collections` CouchDB database be removed, and well as references to the ` CAP_Model::Collections_server` environment variable?  It looks like everything needed is currently in &lt;Component Model::Collections&gt; in CAP/cap.conf

---

The CAP/Dockerfile sets a series of variables which are not mentioned in the docker-compose.override.yml.example 

Can it be confirmed which environment variables and databases are current?

**Comment by SaschaAdler** [comment]
`cap_collections` and `parl_session` are still in use. I can replace them with config in CAP if you need me to.

**Comment by RussellMcOrmond** [comment]
Is is real easy to do? 

It would simplify database configuration if the data is static: meaning edited/generated by platform staff, and thus would be part of the docker image build rather than something outside the image.

**Comment by SaschaAdler** [comment]
I wouldn't say it's real easy but it would be fairly straightforward as the data is either completely static or only changes when other things about portals change.

**Comment by RussellMcOrmond** [comment]
I'm a big fan of encapsulating as much as we can within the Docker containers, reducing cross-dependencies whenever feasible. No rush, but this would be a great enhancement.

**Comment by SaschaAdler** [comment]
#83 allows for the removal of `cap_collections` and `parl_session` databases. I've marked that that PR closes this issue; let me know if you need anything else.
